version: '3'
services:
  srs:
    image: ossrs/srs:3
    ports:
      - 1935:1935
      - 8080:8080
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
  stream-controller:
    build: ./server
    image: stream-controller:latest
    ports:
      - 3000:3000